# Introdução ao PyTorch

In [1]:
import torch

## Perceptron básico

Implmentando o neuronio mais simples, de forma mais simples

In [2]:
def activation(x):
    """
    Função que realiza o calculo da sigmoid
    :param x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [3]:
# Dedinir seed para os valores randomicos que serão usados
torch.manual_seed(7)


# gerando uma matriz com 5 valores aleatorios
features = torch.randn((1,5))
print ('features', features)

# novos valores aleatorios baseados no formato do tensor passado como parametro
weights = torch.randn_like(features)
print ('wights', weights)

bias = torch.randn((1,1))
print ('bias', bias)


features tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
wights tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
bias tensor([[0.3177]])


In [4]:
(features*weights).sum() 

tensor(-1.9796)

In [5]:
def perceptron(features, weights, bias):
    value = (features*weights).sum() + bias
    return activation(value)

In [6]:
perceptron(features, weights, bias)

tensor([[0.1595]])

## Perceptron básico usando multiplicação de matrizes

In [7]:
def perceptron_m(features, weights, bias):
    w = weights.view(weights.shape[::-1]) # corrigindo o formato para a multiplcação de matrizes
    value = torch.mm(features, w) + bias
    return activation(value)

In [8]:
perceptron_m(features, weights, bias)

tensor([[0.1595]])

## Pytorch e Numpy

In [9]:
import numpy as np

In [11]:
a = np.random.rand(3,2)
a

array([[0.48936823, 0.56241628],
       [0.39189073, 0.80232465],
       [0.15762504, 0.44682915]])

In [12]:
b = torch.from_numpy(a)
b

tensor([[0.4894, 0.5624],
        [0.3919, 0.8023],
        [0.1576, 0.4468]], dtype=torch.float64)

In [13]:
b.numpy()

array([[0.48936823, 0.56241628],
       [0.39189073, 0.80232465],
       [0.15762504, 0.44682915]])

Os dados são compartilhados, então a alteração de um afeta o outro

In [14]:
b.mul_(2)

tensor([[0.9787, 1.1248],
        [0.7838, 1.6046],
        [0.3153, 0.8937]], dtype=torch.float64)

In [15]:
a

array([[0.97873645, 1.12483256],
       [0.78378146, 1.6046493 ],
       [0.31525009, 0.89365829]])